Remove kind specific code
primaza/primazactl pull request #37
Opened 2023-07-12 14:44 UTC by filariow

Signed-off-by: Francesco Ilario <filario@redhat.com>

2023-07-12 20:29 UTC, mmulholla requested changes
Code looks fine but the README needs updating with the new flag and some info on how to get the url.
My PR for dry run has quite a few doc updates and will clash, so better if we can merge that first and then update the readme.

2023-07-13 13:00 UTC, mmulholla requested changes
two minor comments.

2023-07-13 13:00 UTC, mmulholla commented on README.md
> +                        path to kubeconfig file, default: KUBECONFIG environment variable if set, otherwise /home/filario/.kube/config
remove ref to /home/filario.

2023-07-13 13:00 UTC, mmulholla commented on README.md
> +                        path to kubeconfig file, default: KUBECONFIG environment variable if set, otherwise /home/filario/.kube/config
remove ref to /home/filario

2023-07-13 15:07 UTC, filariow commented on README.md
> +                        path to kubeconfig file, default: KUBECONFIG environment variable if set, otherwise /home/filario/.kube/config
done

2023-07-13 16:14 UTC, mmulholla approved these changes

2023-07-13 16:15 UTC, merged